### PR TITLE
Capitalise Makefile filename

### PR DESCRIPTION
**Pull request by andygout**
I kept not being able to find the Makefile because I was looking for its name being capitalised.

This creates consistency with how it is written elsewhere throughout Customer Products.

### CODE REVIEW

**Comment by pixelandpage** [comment]
Oh I'm not sure about this 😕 What apps are you trying to be consistent with?

**Comment by andygout** [comment]
At least the 17 apps on which we are currently performing Page Kit migrations: https://github.com/Financial-Times/dotcom-page-kit/issues/794.

**Comment by pixelandpage** [comment]
On the one hand, you've made a strong case for consistency! On the other, we don't use this capitalisation pattern for any other root-level files and I don't mind Page Kit breaking with conventions when we have a good reason to. On balance, I can reluctantly accept this based on the fact that it might improve usability, but I'd be interested to know _why_ we capitalise the `Makefile` in our existing repos - this doesn't seem to be backed by any other conventions.

**Comment by andygout** [comment]
Seems the convention is to capitalise (although the reasoning for this comes from the handling of letter casing only on certain operating systems): https://stackoverflow.com/questions/14368941/is-the-convention-for-naming-make-files-to-use-a-capital-m-such-as-makefile/14368985

Having only ever seen it capitalised means my muscle memory kept missing it in lowercase, so this PR was made exclusively from a usability angle.

Happy to merge or close either way.

**Comment by andygout** [comment]
Agreed offline to close.

**Pull request closed without merging**
