### PR TITLE
Add comment which lists all items in the default set

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by pixelandpage** [comment]
Out of interest, how will we know if this list changes? Does that ever happen?

**Comment by JakeChampion** [comment]
@pixelandpage The default list is a source of confusion for many users of polyfill.io, I've chosen to never update it and instead recommend that people explicitly list what they require.

**Comment by JakeChampion** [comment]
I'll leave this PR for one of the dotcom-page-kit team to merge and release if that is okay

**Comment by i-like-robots** [comment]
Thanks @JakeChampion !

**Pull request merged**
