### PR TITLE
Replace dom-loaded with ready-state

### PR DESCRIPTION
**Pull request by andygout**
Fixes: https://github.com/Financial-Times/dotcom-page-kit/issues/740.

Once this PR is approved I will make the necessary changes in the migration docs: https://github.com/Financial-Times/dotcom-page-kit/wiki/Migrating-from-n%E2%80%93ui-to-Page-Kit.

@apaleslimghost Re. your [comment](https://github.com/Financial-Times/n-tracking/pull/39/files#r373430152) in this n-tracking PR:
- Should we also be using the `ready-state` package in that repo (or have Page Kit wrap it in a function that it can use)?
- Do we also need to identify which other apps that consume Page Kit likewise need this change applied?

#### New dependencies:
- [npm: ready-state](https://www.npmjs.com/package/ready-state).

### CODE REVIEW

**Comment by i-like-robots** [comment]
- https://github.com/Financial-Times/next-subscribe/blob/496e35570989f962fcf0cde8fcd196e1df666707/client/controller.js#L41-L49
- https://github.com/Financial-Times/n-tracking/blob/bfb23d49ea5e872a3a4ff5b3c9f9253336f9599a/src/client/trackers/realUserMonitoringForPerformance.js#L42-L47

**Comment by andygout** [comment]
Re. [`next-subscribe/client/controller.js`](https://github.com/Financial-Times/next-subscribe/blob/master/client/controller.js#L41-L49), the code is enquiring and interacting with `document` via [`this.document`](https://github.com/Financial-Times/next-subscribe/blob/master/client/controller.js#L12), assigned its value from `this.window.document`, with `this.window` having been assigned from a constructor argument of `window`.

However, `ready-state` is not looking for `this.document`, but rather `document`, and so throws `ReferenceError: document is not defined` when it makes any such enquiry: https://github.com/soenkekluth/ready-state/blob/master/ready-state.js#L10.

Options would seem to be:
- Make a PR to `ready-state` to enable it to accommodate `this.document` as well as `document` (👎).
- Rewrite `next-subscribe/client/controller.js` so uses direct references to `window` and `document` rather than `this.window` and `this.document`, but as a class (`Controller`) this feels like the way it should be.
- Leave it as it is without introducing the `ready-state` package.

**Comment by i-like-robots** [comment]
I can only assume it's done the way it is to make mocking out global methods simpler.

It's not completely necessary to adjust this so I wouldn't spend to much time on it. If it's not a straight swap then I'd move on.

**Comment by andygout** [comment]
Re. [`n-tracking/master/src/client/trackers/realUserMonitoringForPerformance.js`](https://github.com/Financial-Times/n-tracking/blob/master/src/client/trackers/realUserMonitoringForPerformance.js#L42-L47), PR is here: https://github.com/Financial-Times/n-tracking/pull/40.

**Pull request merged**
